### ISSUE TITLE
SAAR for NaN value

### ISSUE THREAD

**Issue by kkats** [TEOS-10/GSW-Fortran#10]
In toolbox/gsw_saar.f90

```
59: ndepth_max = -1.0_r8
60: do k = 1,4
61:   if (ndepth_ref(indy0+delj(k),indx0+deli(k)).gt.0.0_r8) &
62:      ndepth_max = max(ndepth_max,ndepth_ref(indy0+delj(k),indx0+deli(k)))
63:  end do
64:
65: if (ndepth_max.eq.-1.0_r8) then
66:    gsw_saar = 0.0_r8 
67:    return
68: end if
```

The snippet above seems to suggest that when SAAR is requested on land, it seems to return a value 0.0. Isn't it better to return `gsw_error_code` ?

**Comment by hylandg** [comment]
This is not a Fortran specific issue - the above code exactly follows the Matlab version (and likewise the C code follows the Fortran version - all of which return 0.0 for SAAR values that are a long way from the ocean). You should ask this question at a higher level - perhaps @PaulMBarker can help. Therefore closing this issue here.

**Comment by PaulMBarker** [comment]
gsw_SAAR should return 0 when it is on land otherwise the entire TEOS-10 concept whould not be applicable to lakes.
